name: mileage_run
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0-216.1.beta <4.0.0'

dependencies:
  # base_widgets:
  #   git:
  #     url: https://github.com/nekohack/base-widgets.git
  #     ref: enhance/boarding-card-cp
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  # google_maps_flutter: ^2.10.1
  google_sign_in: ^6.1.6
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  url_launcher: ^6.1.11
  uuid: ^4.0.0

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  source_gen:

flutter:
  uses-material-design: true
